title: iheartstonks
author:
  name: iheartstonks
  email:

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  deep thoughts by iheartstonks.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iheartstonks.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
remote_theme: "jekyll/minima@4c8597750d754f24c5566862facff772269aab82"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: pretty

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: dark

  # If you want to link only specific pages in the site-navigation, use this and list
  # the `path` property (as represented via Liquid) of the pages in the order they should
  # be rendered.
  nav_pages:
    - about.md
    - posts.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: true

  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Social Media Links
  # Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #
  # Entry keys:
  # * title    Tooltip rendered on hovering over icon.
  # * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  # * url      Full URL of social profile.
  social_links:
    - title: iroksox
      icon: github
      url: "https://github.com/iroksox"
    - title: iheartstonks
      icon: twitter
      url: "https://twitter.com/iheartstonks"
